import{A as p,S as v,i as y,a as f}from"./assets/vendor-BYUds9X1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();document.addEventListener("DOMContentLoaded",function(){const t=document.querySelector(".nav-menu"),o=document.querySelector(".nav-item");t&&o&&t.addEventListener("click",function(e){e.preventDefault(),o.classList.toggle("active")}),document.querySelectorAll(".submenu a").forEach(e=>{e.addEventListener("click",function(s){s.preventDefault();const i=this.getAttribute("href").substring(1),a=document.getElementById(i);a&&(window.scrollTo({top:a.offsetTop-80,behavior:"smooth"}),o.classList.remove("active"))})});const r=document.getElementById("scroll-to-footer"),n=document.getElementById("footer");r&&n&&r.addEventListener("click",function(){window.scrollTo({top:n.offsetTop,behavior:"smooth"})})});document.addEventListener("DOMContentLoaded",()=>{new p(".list-qestions",{duration:500,showMultiple:!0}),document.querySelectorAll(".icon-accordion-close").forEach(o=>{const r=o.closest(".topic-button"),n=r==null?void 0:r.nextElementSibling,e=o.querySelector("use");n&&o.addEventListener("click",()=>{n.style.display==="block"?(n.style.display="none",e.setAttribute("href","/Code-Academy/assets/icons-BXQt0PIq.svg#icon-accordion-closesvg")):(n.style.display="block",e.setAttribute("href","/Code-Academy/assets/icons-BXQt0PIq.svg#icon-accordion-opensvg"))})})});async function w(){try{const{data:t}=await f.get("https://portfolio-js.b.goit.study/api/reviews");return t}catch(t){console.error("Error: ",t)}}function g(t){return t.map(({_id:o,author:r,avatar_url:n,review:e})=>`
		<li class="swiper-slide review-card">
		  <img src="${n}" alt="${r}"/>
			<div class="review-info">
			  <h4>${r}</h4>
				<p>${e}</p>
			</div>
		</li>
		`).join("")}const b=document.querySelector(".reviews-container"),h=document.querySelector(".reviews-list"),d=document.querySelector(".reviews-error"),L=document.querySelector(".swiper-button-prev"),u=document.querySelector(".swiper-button-next");let l=!1;document.addEventListener("DOMContentLoaded",async()=>{try{let r=function(){L.toggleAttribute("disabled",o.isBeginning),u.toggleAttribute("disabled",o.isEnd)};const t=await w();if(!t||t.length===0){d.classList.remove("hidden"),d.classList.add("css-err-mes"),u.setAttribute("disabled","true"),l=!0;return}h.innerHTML=g(t);const o=new v(".swiper",{direction:"horizontal",loop:!1,spaceBetween:16,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:{invert:!0},resizeObserver:!0,slidesPerView:1,breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:4}}});o.on("slideChange",r),r()}catch(t){l=!0,console.error(t)}});const E=new IntersectionObserver(t=>{t.forEach(o=>{l&&o.isIntersecting&&y.error({title:"Error",message:"No feedback data about reviews. We are solving the problem",position:"topRight"})})},{threshold:.2});E.observe(b);const m=document.querySelector(".footer-form"),S=document.querySelector(".btn-close-res"),c=document.querySelector(".modal-window"),q="https://portfolio-js.b.goit.study/api",O="/requests";m.addEventListener("submit",async t=>{t.preventDefault();try{const o=t.currentTarget.elements.email.value.trim(),r=t.currentTarget.elements.comments.value.trim(),n=JSON.stringify({email:o,comment:r}),e=q+O,s=await f.post(e,n,{headers:{accept:"application/json","Content-Type":"application/json"}});c.classList.add("show"),m.reset(),c.addEventListener("click",i=>{c.classList.remove("show")}),document.addEventListener("keydown",i=>{i.key==="Escape"&&c.classList.remove("show")}),S.addEventListener("click",i=>{c.classList.remove("show")})}catch{alert("Error. Please, try again later")}});
//# sourceMappingURL=index.js.map
